
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
# Your branch is up to date with 'origin/master'.
#
# Changes to be committed:
#	new file:   .editorconfig
#	new file:   .sourcemaps/0.js.map
#	new file:   .sourcemaps/1.js.map
#	new file:   .sourcemaps/2.js.map
#	new file:   .sourcemaps/3.js.map
#	new file:   .sourcemaps/4.js.map
#	new file:   .sourcemaps/5.js.map
#	new file:   .sourcemaps/main.js.map
#	new file:   config.xml
#	new file:   ionic.config.json
#	new file:   ionic.starter.json
#	new file:   nouse.gitignore
#	new file:   package-lock.json
#	new file:   package.json
#	new file:   platforms/android/.gitignore
#	new file:   platforms/android/.gradle/4.1/fileChanges/last-build.bin
#	new file:   platforms/android/.gradle/4.1/fileHashes/fileHashes.bin
#	new file:   platforms/android/.gradle/4.1/fileHashes/fileHashes.lock
#	new file:   platforms/android/.gradle/4.6/fileChanges/last-build.bin
#	new file:   platforms/android/.gradle/4.6/fileHashes/fileHashes.bin
#	new file:   platforms/android/.gradle/4.6/fileHashes/fileHashes.lock
#	new file:   platforms/android/.gradle/4.6/taskHistory/taskHistory.bin
#	new file:   platforms/android/.gradle/4.6/taskHistory/taskHistory.lock
#	new file:   platforms/android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
#	new file:   platforms/android/.gradle/buildOutputCleanup/cache.properties
#	new file:   platforms/android/.gradle/buildOutputCleanup/outputFiles.bin
#	new file:   platforms/android/CordovaLib/AndroidManifest.xml
#	new file:   platforms/android/CordovaLib/build.gradle
#	new file:   platforms/android/CordovaLib/cordova.gradle
#	new file:   platforms/android/CordovaLib/project.properties
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/AuthenticationToken.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/BuildHelper.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CallbackContext.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CallbackMap.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/Config.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/ConfigXmlParser.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaActivity.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaArgs.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaBridge.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaClientCertRequest.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaDialogsHelper.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaHttpAuthHandler.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaInterface.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaInterfaceImpl.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaPlugin.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaPreferences.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaResourceApi.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaWebView.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaWebViewEngine.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CordovaWebViewImpl.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/CoreAndroid.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/ExposedJsApi.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/ICordovaClientCertRequest.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/ICordovaCookieManager.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/ICordovaHttpAuthHandler.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/LOG.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/NativeToJsMessageQueue.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/PermissionHelper.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/PluginEntry.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/PluginManager.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/PluginResult.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/ResumeCallback.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/Whitelist.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemExposedJsApi.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemWebChromeClient.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemWebView.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemWebViewClient.java
#	new file:   platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemWebViewEngine.java
#	new file:   platforms/android/android.json
#	new file:   platforms/android/app/build.gradle
#	new file:   platforms/android/app/src/main/AndroidManifest.xml
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/ionicons.eot
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/ionicons.scss
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/ionicons.svg
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/ionicons.ttf
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/ionicons.woff
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/ionicons.woff2
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/noto-sans-bold.ttf
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/noto-sans-bold.woff
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/noto-sans-regular.ttf
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/noto-sans-regular.woff
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/noto-sans.scss
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-bold.ttf
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-bold.woff
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-bold.woff2
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-light.ttf
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-light.woff
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-light.woff2
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-medium.ttf
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-medium.woff
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-medium.woff2
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-regular.ttf
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-regular.woff
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto-regular.woff2
#	new file:   platforms/android/app/src/main/assets/www/assets/fonts/roboto.scss
#	new file:   platforms/android/app/src/main/assets/www/assets/icon/favicon.ico
#	new file:   platforms/android/app/src/main/assets/www/assets/imgs/iform-bg.png
#	new file:   platforms/android/app/src/main/assets/www/assets/imgs/logo.png
#	new file:   platforms/android/app/src/main/assets/www/build/0.js
#	new file:   platforms/android/app/src/main/assets/www/build/0.js.map
#	new file:   platforms/android/app/src/main/assets/www/build/1.js
#	new file:   platforms/android/app/src/main/assets/www/build/1.js.map
#	new file:   platforms/android/app/src/main/assets/www/build/2.js
#	new file:   platforms/android/app/src/main/assets/www/build/2.js.map
#	new file:   platforms/android/app/src/main/assets/www/build/3.js
#	new file:   platforms/android/app/src/main/assets/www/build/3.js.map
#	new file:   platforms/android/app/src/main/assets/www/build/4.js
#	new file:   platforms/android/app/src/main/assets/www/build/4.js.map
#	new file:   platforms/android/app/src/main/assets/www/build/5.js
#	new file:   platforms/android/app/src/main/assets/www/build/5.js.map
#	new file:   platforms/android/app/src/main/assets/www/build/main.css
#	new file:   platforms/android/app/src/main/assets/www/build/main.css.map
#	new file:   platforms/android/app/src/main/assets/www/build/main.js
#	new file:   platforms/android/app/src/main/assets/www/build/main.js.map
#	new file:   platforms/android/app/src/main/assets/www/build/polyfills.js
#	new file:   platforms/android/app/src/main/assets/www/build/sw-toolbox.js
#	new file:   platforms/android/app/src/main/assets/www/build/vendor.js
#	new file:   platforms/android/app/src/main/assets/www/build/vendor.js.map
#	new file:   platforms/android/app/src/main/assets/www/cordova-js-src/android/nativeapiprovider.js
#	new file:   platforms/android/app/src/main/assets/www/cordova-js-src/android/promptbasednativeapi.js
#	new file:   platforms/android/app/src/main/assets/www/cordova-js-src/exec.js
#	new file:   platforms/android/app/src/main/assets/www/cordova-js-src/platform.js
#	new file:   platforms/android/app/src/main/assets/www/cordova-js-src/plugin/android/app.js
#	new file:   platforms/android/app/src/main/assets/www/cordova.js
#	new file:   platforms/android/app/src/main/assets/www/cordova_plugins.js
#	new file:   platforms/android/app/src/main/assets/www/index.html
#	new file:   platforms/android/app/src/main/assets/www/manifest.json
#	new file:   platforms/android/app/src/main/assets/www/plugins/cordova-plugin-device/www/device.js
#	new file:   platforms/android/app/src/main/assets/www/plugins/cordova-plugin-ionic-keyboard/www/android/keyboard.js
#	new file:   platforms/android/app/src/main/assets/www/plugins/cordova-plugin-ionic-webview/src/www/util.js
#	new file:   platforms/android/app/src/main/assets/www/plugins/cordova-plugin-splashscreen/www/splashscreen.js
#	new file:   platforms/android/app/src/main/assets/www/plugins/cordova-plugin-statusbar/www/statusbar.js
#	new file:   platforms/android/app/src/main/assets/www/service-worker.js
#	new file:   platforms/android/app/src/main/java/com/ionicframework/cordova/webview/AndroidProtocolHandler.java
#	new file:   platforms/android/app/src/main/java/com/ionicframework/cordova/webview/IonicWebView.java
#	new file:   platforms/android/app/src/main/java/com/ionicframework/cordova/webview/IonicWebViewEngine.java
#	new file:   platforms/android/app/src/main/java/com/ionicframework/cordova/webview/UriMatcher.java
#	new file:   platforms/android/app/src/main/java/com/ionicframework/cordova/webview/WebViewLocalServer.java
#	new file:   platforms/android/app/src/main/java/io/ionic/keyboard/IonicKeyboard.java
#	new file:   platforms/android/app/src/main/java/io/ionic/starter/MainActivity.java
#	new file:   platforms/android/app/src/main/java/org/apache/cordova/device/Device.java
#	new file:   platforms/android/app/src/main/java/org/apache/cordova/splashscreen/SplashScreen.java
#	new file:   platforms/android/app/src/main/java/org/apache/cordova/statusbar/StatusBar.java
#	new file:   platforms/android/app/src/main/java/org/apache/cordova/whitelist/WhitelistPlugin.java
#	new file:   platforms/android/app/src/main/res/drawable-land-hdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-land-ldpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-land-mdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-land-xhdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-land-xxhdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-land-xxxhdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-port-hdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-port-ldpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-port-mdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-port-xhdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-port-xxhdpi/screen.png
#	new file:   platforms/android/app/src/main/res/drawable-port-xxxhdpi/screen.png
#	new file:   platforms/android/app/src/main/res/mipmap-hdpi/icon.png
#	new file:   platforms/android/app/src/main/res/mipmap-ldpi/icon.png
#	new file:   platforms/android/app/src/main/res/mipmap-mdpi/icon.png
#	new file:   platforms/android/app/src/main/res/mipmap-xhdpi/icon.png
#	new file:   platforms/android/app/src/main/res/mipmap-xxhdpi/icon.png
#	new file:   platforms/android/app/src/main/res/mipmap-xxxhdpi/icon.png
#	new file:   platforms/android/app/src/main/res/values/strings.xml
#	new file:   platforms/android/app/src/main/res/xml/config.xml
#	new file:   platforms/android/build.gradle
#	new file:   platforms/android/cordova/Api.js
#	new file:   platforms/android/cordova/android_sdk_version
#	new file:   platforms/android/cordova/android_sdk_version.bat
#	new file:   platforms/android/cordova/build
#	new file:   platforms/android/cordova/build.bat
#	new file:   platforms/android/cordova/check_reqs
#	new file:   platforms/android/cordova/check_reqs.bat
#	new file:   platforms/android/cordova/clean
#	new file:   platforms/android/cordova/clean.bat
#	new file:   platforms/android/cordova/defaults.xml
#	new file:   platforms/android/cordova/lib/Adb.js
#	new file:   platforms/android/cordova/lib/AndroidManifest.js
#	new file:   platforms/android/cordova/lib/AndroidProject.js
#	new file:   platforms/android/cordova/lib/AndroidStudio.js
#	new file:   platforms/android/cordova/lib/android_sdk.js
#	new file:   platforms/android/cordova/lib/build.js
#	new file:   platforms/android/cordova/lib/builders/GenericBuilder.js
#	new file:   platforms/android/cordova/lib/builders/GradleBuilder.js
#	new file:   platforms/android/cordova/lib/builders/StudioBuilder.js
#	new file:   platforms/android/cordova/lib/builders/builders.js
#	new file:   platforms/android/cordova/lib/check_reqs.js
#	new file:   platforms/android/cordova/lib/device.js
#	new file:   platforms/android/cordova/lib/emulator.js
#	new file:   platforms/android/cordova/lib/getASPath.bat
#	new file:   platforms/android/cordova/lib/install-device
#	new file:   platforms/android/cordova/lib/install-device.bat
#	new file:   platforms/android/cordova/lib/install-emulator
#	new file:   platforms/android/cordova/lib/install-emulator.bat
#	new file:   platforms/android/cordova/lib/list-devices
#	new file:   platforms/android/cordova/lib/list-devices.bat
#	new file:   platforms/android/cordova/lib/list-emulator-images
#	new file:   platforms/android/cordova/lib/list-emulator-images.bat
#	new file:   platforms/android/cordova/lib/list-started-emulators
#	new file:   platforms/android/cordova/lib/list-started-emulators.bat
#	new file:   platforms/android/cordova/lib/log.js
#	new file:   platforms/android/cordova/lib/plugin-build.gradle
#	new file:   platforms/android/cordova/lib/pluginHandlers.js
#	new file:   platforms/android/cordova/lib/prepare.js
#	new file:   platforms/android/cordova/lib/retry.js
#	new file:   platforms/android/cordova/lib/run.js
#	new file:   platforms/android/cordova/lib/start-emulator
#	new file:   platforms/android/cordova/lib/start-emulator.bat
#	new file:   platforms/android/cordova/log
#	new file:   platforms/android/cordova/log.bat
#	new file:   platforms/android/cordova/loggingHelper.js
#	new file:   platforms/android/cordova/run
#	new file:   platforms/android/cordova/run.bat
#	new file:   platforms/android/cordova/version
#	new file:   platforms/android/cordova/version.bat
#	new file:   platforms/android/platform_www/cordova-js-src/android/nativeapiprovider.js
#	new file:   platforms/android/platform_www/cordova-js-src/android/promptbasednativeapi.js
#	new file:   platforms/android/platform_www/cordova-js-src/exec.js
#	new file:   platforms/android/platform_www/cordova-js-src/platform.js
#	new file:   platforms/android/platform_www/cordova-js-src/plugin/android/app.js
#	new file:   platforms/android/platform_www/cordova.js
#	new file:   platforms/android/platform_www/cordova_plugins.js
#	new file:   platforms/android/platform_www/plugins/cordova-plugin-device/www/device.js
#	new file:   platforms/android/platform_www/plugins/cordova-plugin-ionic-keyboard/www/android/keyboard.js
#	new file:   platforms/android/platform_www/plugins/cordova-plugin-ionic-webview/src/www/util.js
#	new file:   platforms/android/platform_www/plugins/cordova-plugin-splashscreen/www/splashscreen.js
#	new file:   platforms/android/platform_www/plugins/cordova-plugin-statusbar/www/statusbar.js
#	new file:   platforms/android/project.properties
#	new file:   platforms/android/settings.gradle
#	new file:   platforms/android/wrapper.gradle
#	new file:   platforms/ios/.gitignore
#	new file:   platforms/ios/CordovaLib/Classes/Private/CDVDebug.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/CDVJSON_private.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/CDVJSON_private.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/CDVPlugin+Private.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVGestureHandler/CDVGestureHandler.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVGestureHandler/CDVGestureHandler.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVHandleOpenURL/CDVHandleOpenURL.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVHandleOpenURL/CDVHandleOpenURL.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVIntentAndNavigationFilter.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVIntentAndNavigationFilter.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVLocalStorage/CDVLocalStorage.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVLocalStorage/CDVLocalStorage.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVLogger/CDVLogger.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVLogger/CDVLogger.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewDelegate.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewDelegate.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewEngine.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewEngine.m
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewNavigationDelegate.h
#	new file:   platforms/ios/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewNavigationDelegate.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDV.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVAppDelegate.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVAppDelegate.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVAvailability.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVAvailabilityDeprecated.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVCommandDelegate.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVCommandDelegateImpl.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVCommandDelegateImpl.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVCommandQueue.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVCommandQueue.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVConfigParser.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVConfigParser.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVInvokedUrlCommand.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVInvokedUrlCommand.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVPlugin+Resources.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVPlugin+Resources.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVPlugin.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVPlugin.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVPluginResult.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVPluginResult.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVScreenOrientationDelegate.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVTimer.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVTimer.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVURLProtocol.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVUserAgentUtil.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVUserAgentUtil.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVViewController.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVViewController.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVWebViewEngineProtocol.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVWhitelist.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/CDVWhitelist.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/NSDictionary+CordovaPreferences.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/NSDictionary+CordovaPreferences.m
#	new file:   platforms/ios/CordovaLib/Classes/Public/NSMutableArray+QueueAdditions.h
#	new file:   platforms/ios/CordovaLib/Classes/Public/NSMutableArray+QueueAdditions.m
#	new file:   platforms/ios/CordovaLib/CordovaLib.xcodeproj/project.pbxproj
#	new file:   platforms/ios/CordovaLib/CordovaLib_Prefix.pch
#	new file:   platforms/ios/CordovaLib/VERSION
#	new file:   platforms/ios/CordovaLib/cordova.js
#	new file:   platforms/ios/cordova/Api.js
#	new file:   platforms/ios/cordova/apple_ios_version
#	new file:   platforms/ios/cordova/apple_osx_version
#	new file:   platforms/ios/cordova/apple_xcode_version
#	new file:   platforms/ios/cordova/build
#	new file:   platforms/ios/cordova/build-debug.xcconfig
#	new file:   platforms/ios/cordova/build-extras.xcconfig
#	new file:   platforms/ios/cordova/build-release.xcconfig
#	new file:   platforms/ios/cordova/build.bat
#	new file:   platforms/ios/cordova/build.xcconfig
#	new file:   platforms/ios/cordova/check_reqs
#	new file:   platforms/ios/cordova/check_reqs.bat
#	new file:   platforms/ios/cordova/clean
#	new file:   platforms/ios/cordova/clean.bat
#	new file:   platforms/ios/cordova/defaults.xml
#	new file:   platforms/ios/cordova/lib/Podfile.js
#	new file:   platforms/ios/cordova/lib/PodsJson.js
#	new file:   platforms/ios/cordova/lib/build.js
#	new file:   platforms/ios/cordova/lib/check_reqs.js
#	new file:   platforms/ios/cordova/lib/clean.js
#	new file:   platforms/ios/cordova/lib/copy-www-build-step.js
#	new file:   platforms/ios/cordova/lib/list-devices
#	new file:   platforms/ios/cordova/lib/list-emulator-build-targets
#	new file:   platforms/ios/cordova/lib/list-emulator-images
#	new file:   platforms/ios/cordova/lib/list-started-emulators
#	new file:   platforms/ios/cordova/lib/plugman/pluginHandlers.js
#	new file:   platforms/ios/cordova/lib/prepare.js
#	new file:   platforms/ios/cordova/lib/projectFile.js
#	new file:   platforms/ios/cordova/lib/run.js
#	new file:   platforms/ios/cordova/lib/spawn.js
#	new file:   platforms/ios/cordova/lib/start-emulator
#	new file:   platforms/ios/cordova/lib/versions.js
#	new file:   platforms/ios/cordova/log
#	new file:   platforms/ios/cordova/log.bat
#	new file:   platforms/ios/cordova/loggingHelper.js
#	new file:   platforms/ios/cordova/run
#	new file:   platforms/ios/cordova/run.bat
#	new file:   platforms/ios/cordova/version
#	new file:   platforms/ios/cordova/version.bat
#	new file:   platforms/ios/frameworks.json
#	new file:   platforms/ios/iForms.xcodeproj/project.pbxproj
#	new file:   platforms/ios/iForms.xcworkspace/contents.xcworkspacedata
#	new file:   platforms/ios/iForms.xcworkspace/xcshareddata/xcschemes/iForms.xcscheme
#	new file:   platforms/ios/iForms/.gitignore
#	new file:   platforms/ios/iForms/Bridging-Header.h
#	new file:   platforms/ios/iForms/CDVLaunchScreen.storyboard
#	new file:   platforms/ios/iForms/Classes/AppDelegate.h
#	new file:   platforms/ios/iForms/Classes/AppDelegate.m
#	new file:   platforms/ios/iForms/Classes/MainViewController.h
#	new file:   platforms/ios/iForms/Classes/MainViewController.m
#	new file:   platforms/ios/iForms/Classes/MainViewController.xib
#	new file:   platforms/ios/iForms/Entitlements-Debug.plist
#	new file:   platforms/ios/iForms/Entitlements-Release.plist
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/AppIcon29x29@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/AppIcon29x29@3x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/AppIcon40x40@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/Contents.json
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-1024.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-20@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-20@3x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-40.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-40@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-50.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-50@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-60@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-60@3x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-72.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-72@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-76.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-76@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-83.5@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-small.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-small@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon-small@3x.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon.png
#	new file:   platforms/ios/iForms/Images.xcassets/AppIcon.appiconset/icon@2x.png
#	new file:   platforms/ios/iForms/Images.xcassets/Contents.json
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Contents.json
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-568h@2x~iphone.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-667h.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-736h.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-Landscape-736h.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-Landscape@2x~ipad.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-Landscape~ipad.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-Portrait@2x~ipad.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default-Portrait~ipad.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default@2x~iphone.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchImage.launchimage/Default~iphone.png
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchStoryboard.imageset/Contents.json
#	new file:   platforms/ios/iForms/Images.xcassets/LaunchStoryboard.imageset/Default@2x~universal~anyany.png
#	new file:   platforms/ios/iForms/Plugins/README
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-device/CDVDevice.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-device/CDVDevice.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-keyboard/CDVIonicKeyboard.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-keyboard/CDVIonicKeyboard.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/CDVWKProcessPoolFactory.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/CDVWKProcessPoolFactory.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/CDVWKWebViewEngine.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/CDVWKWebViewEngine.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/CDVWKWebViewUIDelegate.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/CDVWKWebViewUIDelegate.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServer.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServer.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerConnection.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerConnection.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerDataRequest.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerDataRequest.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerDataResponse.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerDataResponse.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerErrorResponse.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerErrorResponse.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerFileRequest.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerFileRequest.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerFileResponse.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerFileResponse.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerFunctions.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerFunctions.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerHTTPStatusCodes.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerMultiPartFormRequest.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerMultiPartFormRequest.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerPrivate.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerRequest.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerRequest.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerResponse.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerResponse.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerStreamedResponse.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerStreamedResponse.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerURLEncodedFormRequest.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-ionic-webview/GCDWebServerURLEncodedFormRequest.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-splashscreen/CDVSplashScreen.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-splashscreen/CDVSplashScreen.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-splashscreen/CDVViewController+SplashScreen.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-splashscreen/CDVViewController+SplashScreen.m
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-statusbar/CDVStatusBar.h
#	new file:   platforms/ios/iForms/Plugins/cordova-plugin-statusbar/CDVStatusBar.m
#	new file:   platforms/ios/iForms/config.xml
#	new file:   platforms/ios/iForms/iForms-Info.plist
#	new file:   platforms/ios/iForms/iForms-Prefix.pch
#	new file:   platforms/ios/iForms/main.m
#	new file:   platforms/ios/ios.json
#	new file:   platforms/ios/platform_www/cordova-js-src/exec.js
#	new file:   platforms/ios/platform_www/cordova-js-src/platform.js
#	new file:   platforms/ios/platform_www/cordova-js-src/plugin/ios/console.js
#	new file:   platforms/ios/platform_www/cordova-js-src/plugin/ios/logger.js
#	new file:   platforms/ios/platform_www/cordova.js
#	new file:   platforms/ios/platform_www/cordova_plugins.js
#	new file:   platforms/ios/platform_www/plugins/cordova-plugin-device/www/device.js
#	new file:   platforms/ios/platform_www/plugins/cordova-plugin-ionic-keyboard/www/ios/keyboard.js
#	new file:   platforms/ios/platform_www/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js
#	new file:   platforms/ios/platform_www/plugins/cordova-plugin-ionic-webview/src/www/util.js
#	new file:   platforms/ios/platform_www/plugins/cordova-plugin-splashscreen/www/splashscreen.js
#	new file:   platforms/ios/platform_www/plugins/cordova-plugin-statusbar/www/statusbar.js
#	new file:   platforms/ios/platform_www/wk-plugin.js
#	new file:   platforms/ios/pods-debug.xcconfig
#	new file:   platforms/ios/pods-release.xcconfig
#	new file:   platforms/ios/www/assets/fonts/ionicons.eot
#	new file:   platforms/ios/www/assets/fonts/ionicons.scss
#	new file:   platforms/ios/www/assets/fonts/ionicons.svg
#	new file:   platforms/ios/www/assets/fonts/ionicons.ttf
#	new file:   platforms/ios/www/assets/fonts/ionicons.woff
#	new file:   platforms/ios/www/assets/fonts/ionicons.woff2
#	new file:   platforms/ios/www/assets/fonts/noto-sans-bold.ttf
#	new file:   platforms/ios/www/assets/fonts/noto-sans-bold.woff
#	new file:   platforms/ios/www/assets/fonts/noto-sans-regular.ttf
#	new file:   platforms/ios/www/assets/fonts/noto-sans-regular.woff
#	new file:   platforms/ios/www/assets/fonts/noto-sans.scss
#	new file:   platforms/ios/www/assets/fonts/roboto-bold.ttf
#	new file:   platforms/ios/www/assets/fonts/roboto-bold.woff
#	new file:   platforms/ios/www/assets/fonts/roboto-bold.woff2
#	new file:   platforms/ios/www/assets/fonts/roboto-light.ttf
#	new file:   platforms/ios/www/assets/fonts/roboto-light.woff
#	new file:   platforms/ios/www/assets/fonts/roboto-light.woff2
#	new file:   platforms/ios/www/assets/fonts/roboto-medium.ttf
#	new file:   platforms/ios/www/assets/fonts/roboto-medium.woff
#	new file:   platforms/ios/www/assets/fonts/roboto-medium.woff2
#	new file:   platforms/ios/www/assets/fonts/roboto-regular.ttf
#	new file:   platforms/ios/www/assets/fonts/roboto-regular.woff
#	new file:   platforms/ios/www/assets/fonts/roboto-regular.woff2
#	new file:   platforms/ios/www/assets/fonts/roboto.scss
#	new file:   platforms/ios/www/assets/icon/favicon.ico
#	new file:   platforms/ios/www/assets/imgs/iform-bg.png
#	new file:   platforms/ios/www/assets/imgs/logo.png
#	new file:   platforms/ios/www/cordova-js-src/exec.js
#	new file:   platforms/ios/www/cordova-js-src/platform.js
#	new file:   platforms/ios/www/cordova-js-src/plugin/ios/console.js
#	new file:   platforms/ios/www/cordova-js-src/plugin/ios/logger.js
#	new file:   platforms/ios/www/cordova.js
#	new file:   platforms/ios/www/cordova_plugins.js
#	new file:   platforms/ios/www/index.html
#	new file:   platforms/ios/www/manifest.json
#	new file:   platforms/ios/www/plugins/cordova-plugin-device/www/device.js
#	new file:   platforms/ios/www/plugins/cordova-plugin-ionic-keyboard/www/ios/keyboard.js
#	new file:   platforms/ios/www/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js
#	new file:   platforms/ios/www/plugins/cordova-plugin-ionic-webview/src/www/util.js
#	new file:   platforms/ios/www/plugins/cordova-plugin-splashscreen/www/splashscreen.js
#	new file:   platforms/ios/www/plugins/cordova-plugin-statusbar/www/statusbar.js
#	new file:   platforms/ios/www/service-worker.js
#	new file:   platforms/ios/www/wk-plugin.js
#	new file:   plugins/android.json
#	new file:   plugins/cordova-plugin-device/CONTRIBUTING.md
#	new file:   plugins/cordova-plugin-device/LICENSE
#	new file:   plugins/cordova-plugin-device/NOTICE
#	new file:   plugins/cordova-plugin-device/README.md
#	new file:   plugins/cordova-plugin-device/RELEASENOTES.md
#	new file:   plugins/cordova-plugin-device/doc/de/README.md
#	new file:   plugins/cordova-plugin-device/doc/de/index.md
#	new file:   plugins/cordova-plugin-device/doc/es/README.md
#	new file:   plugins/cordova-plugin-device/doc/es/index.md
#	new file:   plugins/cordova-plugin-device/doc/fr/README.md
#	new file:   plugins/cordova-plugin-device/doc/fr/index.md
#	new file:   plugins/cordova-plugin-device/doc/it/README.md
#	new file:   plugins/cordova-plugin-device/doc/it/index.md
#	new file:   plugins/cordova-plugin-device/doc/ja/README.md
#	new file:   plugins/cordova-plugin-device/doc/ja/index.md
#	new file:   plugins/cordova-plugin-device/doc/ko/README.md
#	new file:   plugins/cordova-plugin-device/doc/ko/index.md
#	new file:   plugins/cordova-plugin-device/doc/pl/README.md
#	new file:   plugins/cordova-plugin-device/doc/pl/index.md
#	new file:   plugins/cordova-plugin-device/doc/ru/index.md
#	new file:   plugins/cordova-plugin-device/doc/zh/README.md
#	new file:   plugins/cordova-plugin-device/doc/zh/index.md
#	new file:   plugins/cordova-plugin-device/package.json
#	new file:   plugins/cordova-plugin-device/plugin.xml
#	new file:   plugins/cordova-plugin-device/src/android/Device.java
#	new file:   plugins/cordova-plugin-device/src/browser/DeviceProxy.js
#	new file:   plugins/cordova-plugin-device/src/ios/CDVDevice.h
#	new file:   plugins/cordova-plugin-device/src/ios/CDVDevice.m
#	new file:   plugins/cordova-plugin-device/src/osx/CDVDevice.h
#	new file:   plugins/cordova-plugin-device/src/osx/CDVDevice.m
#	new file:   plugins/cordova-plugin-device/src/windows/DeviceProxy.js
#	new file:   plugins/cordova-plugin-device/tests/package.json
#	new file:   plugins/cordova-plugin-device/tests/plugin.xml
#	new file:   plugins/cordova-plugin-device/tests/tests.js
#	new file:   plugins/cordova-plugin-device/types/index.d.ts
#	new file:   plugins/cordova-plugin-device/www/device.js
#	new file:   plugins/cordova-plugin-ionic-keyboard/LICENSE
#	new file:   plugins/cordova-plugin-ionic-keyboard/README.md
#	new file:   plugins/cordova-plugin-ionic-keyboard/package.json
#	new file:   plugins/cordova-plugin-ionic-keyboard/plugin.xml
#	new file:   plugins/cordova-plugin-ionic-keyboard/src/android/IonicKeyboard.java
#	new file:   plugins/cordova-plugin-ionic-keyboard/src/ios/CDVIonicKeyboard.h
#	new file:   plugins/cordova-plugin-ionic-keyboard/src/ios/CDVIonicKeyboard.m
#	new file:   plugins/cordova-plugin-ionic-keyboard/www/android/keyboard.js
#	new file:   plugins/cordova-plugin-ionic-keyboard/www/ios/keyboard.js
#	new file:   plugins/cordova-plugin-ionic-webview/CHANGELOG.md
#	new file:   plugins/cordova-plugin-ionic-webview/CONTRIBUTING.md
#	new file:   plugins/cordova-plugin-ionic-webview/LICENSE
#	new file:   plugins/cordova-plugin-ionic-webview/README.md
#	new file:   plugins/cordova-plugin-ionic-webview/package.json
#	new file:   plugins/cordova-plugin-ionic-webview/plugin.xml
#	new file:   plugins/cordova-plugin-ionic-webview/src/android/com/ionicframework/cordova/webview/AndroidProtocolHandler.java
#	new file:   plugins/cordova-plugin-ionic-webview/src/android/com/ionicframework/cordova/webview/IonicWebView.java
#	new file:   plugins/cordova-plugin-ionic-webview/src/android/com/ionicframework/cordova/webview/IonicWebViewEngine.java
#	new file:   plugins/cordova-plugin-ionic-webview/src/android/com/ionicframework/cordova/webview/UriMatcher.java
#	new file:   plugins/cordova-plugin-ionic-webview/src/android/com/ionicframework/cordova/webview/WebViewLocalServer.java
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/CDVWKProcessPoolFactory.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/CDVWKProcessPoolFactory.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/CDVWKWebViewEngine.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/CDVWKWebViewEngine.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/CDVWKWebViewUIDelegate.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/CDVWKWebViewUIDelegate.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServer.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServer.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerConnection.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerConnection.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerFunctions.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerFunctions.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerHTTPStatusCodes.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerPrivate.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerRequest.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerRequest.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerResponse.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Core/GCDWebServerResponse.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerDataRequest.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerDataRequest.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerFileRequest.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerFileRequest.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerMultiPartFormRequest.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerMultiPartFormRequest.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerURLEncodedFormRequest.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Requests/GCDWebServerURLEncodedFormRequest.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerDataResponse.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerDataResponse.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerErrorResponse.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerErrorResponse.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerFileResponse.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerFileResponse.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerStreamedResponse.h
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/GCDWebServer/Responses/GCDWebServerStreamedResponse.m
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/LICENSE
#	new file:   plugins/cordova-plugin-ionic-webview/src/ios/wk-plugin.js
#	new file:   plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js
#	new file:   plugins/cordova-plugin-ionic-webview/src/www/util.js
#	new file:   plugins/cordova-plugin-splashscreen/CONTRIBUTING.md
#	new file:   plugins/cordova-plugin-splashscreen/LICENSE
#	new file:   plugins/cordova-plugin-splashscreen/NOTICE
#	new file:   plugins/cordova-plugin-splashscreen/README.md
#	new file:   plugins/cordova-plugin-splashscreen/RELEASENOTES.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/de/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/de/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/es/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/es/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/fr/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/fr/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/it/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/it/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/ja/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/ja/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/ko/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/ko/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/pl/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/pl/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/ru/index.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/zh/README.md
#	new file:   plugins/cordova-plugin-splashscreen/doc/zh/index.md
#	new file:   plugins/cordova-plugin-splashscreen/package.json
#	new file:   plugins/cordova-plugin-splashscreen/plugin.xml
#	new file:   plugins/cordova-plugin-splashscreen/src/android/SplashScreen.java
#	new file:   plugins/cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js
#	new file:   plugins/cordova-plugin-splashscreen/src/ios/CDVSplashScreen.h
#	new file:   plugins/cordova-plugin-splashscreen/src/ios/CDVSplashScreen.m
#	new file:   plugins/cordova-plugin-splashscreen/src/ios/CDVViewController+SplashScreen.h
#	new file:   plugins/cordova-plugin-splashscreen/src/ios/CDVViewController+SplashScreen.m
#	new file:   plugins/cordova-plugin-splashscreen/src/wp/ResolutionHelper.cs
#	new file:   plugins/cordova-plugin-splashscreen/src/wp/SplashScreen.cs
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest.xcworkspace/contents.xcworkspacedata
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest.xcworkspace/xcshareddata/CDVSplashScreenTest.xccheckout
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest.xcworkspace/xcshareddata/xcschemes/CordovaLib.xcscheme
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/.npmignore
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenLibTests/ImageNameTest.m
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenLibTests/ImageNameTestDelegates.h
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenLibTests/ImageNameTestDelegates.m
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenLibTests/Info.plist
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenTest.xcodeproj/project.pbxproj
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenTest.xcodeproj/project.xcworkspace/xcshareddata/CDVSplashScreenTest.xccheckout
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenTest.xcodeproj/xcshareddata/xcschemes/CDVSplashScreenLib.xcscheme
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/CDVSplashScreenTest/CDVSplashScreenTest.xcodeproj/xcshareddata/xcschemes/CDVSplashScreenLibTests.xcscheme
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/de/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/es/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/fr/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/it/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/ja/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/ko/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/pl/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/doc/zh/README.md
#	new file:   plugins/cordova-plugin-splashscreen/tests/ios/package.json
#	new file:   plugins/cordova-plugin-splashscreen/tests/package.json
#	new file:   plugins/cordova-plugin-splashscreen/tests/plugin.xml
#	new file:   plugins/cordova-plugin-splashscreen/tests/tests.js
#	new file:   plugins/cordova-plugin-splashscreen/types/index.d.ts
#	new file:   plugins/cordova-plugin-splashscreen/www/splashscreen.js
#	new file:   plugins/cordova-plugin-splashscreen/www/windows/SplashScreenProxy.js
#	new file:   plugins/cordova-plugin-statusbar/CONTRIBUTING.md
#	new file:   plugins/cordova-plugin-statusbar/LICENSE
#	new file:   plugins/cordova-plugin-statusbar/NOTICE
#	new file:   plugins/cordova-plugin-statusbar/README.md
#	new file:   plugins/cordova-plugin-statusbar/RELEASENOTES.md
#	new file:   plugins/cordova-plugin-statusbar/doc/de/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/de/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/es/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/es/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/fr/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/fr/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/it/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/it/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/ja/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/ja/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/ko/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/ko/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/pl/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/pl/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/ru/index.md
#	new file:   plugins/cordova-plugin-statusbar/doc/zh/README.md
#	new file:   plugins/cordova-plugin-statusbar/doc/zh/index.md
#	new file:   plugins/cordova-plugin-statusbar/package.json
#	new file:   plugins/cordova-plugin-statusbar/plugin.xml
#	new file:   plugins/cordova-plugin-statusbar/src/android/StatusBar.java
#	new file:   plugins/cordova-plugin-statusbar/src/browser/StatusBarProxy.js
#	new file:   plugins/cordova-plugin-statusbar/src/ios/CDVStatusBar.h
#	new file:   plugins/cordova-plugin-statusbar/src/ios/CDVStatusBar.m
#	new file:   plugins/cordova-plugin-statusbar/src/windows/StatusBarProxy.js
#	new file:   plugins/cordova-plugin-statusbar/src/wp/StatusBar.cs
#	new file:   plugins/cordova-plugin-statusbar/tests/package.json
#	new file:   plugins/cordova-plugin-statusbar/tests/plugin.xml
#	new file:   plugins/cordova-plugin-statusbar/tests/tests.js
#	new file:   plugins/cordova-plugin-statusbar/types/index.d.ts
#	new file:   plugins/cordova-plugin-statusbar/www/statusbar.js
#	new file:   plugins/cordova-plugin-whitelist/CONTRIBUTING.md
#	new file:   plugins/cordova-plugin-whitelist/LICENSE
#	new file:   plugins/cordova-plugin-whitelist/NOTICE
#	new file:   plugins/cordova-plugin-whitelist/README.md
#	new file:   plugins/cordova-plugin-whitelist/RELEASENOTES.md
#	new file:   plugins/cordova-plugin-whitelist/doc/de/README.md
#	new file:   plugins/cordova-plugin-whitelist/doc/es/README.md
#	new file:   plugins/cordova-plugin-whitelist/doc/fr/README.md
#	new file:   plugins/cordova-plugin-whitelist/doc/it/README.md
#	new file:   plugins/cordova-plugin-whitelist/doc/ja/README.md
#	new file:   plugins/cordova-plugin-whitelist/doc/ko/README.md
#	new file:   plugins/cordova-plugin-whitelist/doc/pl/README.md
#	new file:   plugins/cordova-plugin-whitelist/doc/zh/README.md
#	new file:   plugins/cordova-plugin-whitelist/package.json
#	new file:   plugins/cordova-plugin-whitelist/plugin.xml
#	new file:   plugins/cordova-plugin-whitelist/src/android/WhitelistPlugin.java
#	new file:   plugins/fetch.json
#	new file:   plugins/ios.json
#	new file:   resources/README.md
#	new file:   resources/android/icon/drawable-hdpi-icon.png
#	new file:   resources/android/icon/drawable-ldpi-icon.png
#	new file:   resources/android/icon/drawable-mdpi-icon.png
#	new file:   resources/android/icon/drawable-xhdpi-icon.png
#	new file:   resources/android/icon/drawable-xxhdpi-icon.png
#	new file:   resources/android/icon/drawable-xxxhdpi-icon.png
#	new file:   resources/android/splash/drawable-land-hdpi-screen.png
#	new file:   resources/android/splash/drawable-land-ldpi-screen.png
#	new file:   resources/android/splash/drawable-land-mdpi-screen.png
#	new file:   resources/android/splash/drawable-land-xhdpi-screen.png
#	new file:   resources/android/splash/drawable-land-xxhdpi-screen.png
#	new file:   resources/android/splash/drawable-land-xxxhdpi-screen.png
#	new file:   resources/android/splash/drawable-port-hdpi-screen.png
#	new file:   resources/android/splash/drawable-port-ldpi-screen.png
#	new file:   resources/android/splash/drawable-port-mdpi-screen.png
#	new file:   resources/android/splash/drawable-port-xhdpi-screen.png
#	new file:   resources/android/splash/drawable-port-xxhdpi-screen.png
#	new file:   resources/android/splash/drawable-port-xxxhdpi-screen.png
#	new file:   resources/icon.png
#	new file:   resources/icon.png.md5
#	new file:   resources/ios/icon/icon-1024.png
#	new file:   resources/ios/icon/icon-40.png
#	new file:   resources/ios/icon/icon-40@2x.png
#	new file:   resources/ios/icon/icon-40@3x.png
#	new file:   resources/ios/icon/icon-50.png
#	new file:   resources/ios/icon/icon-50@2x.png
#	new file:   resources/ios/icon/icon-60.png
#	new file:   resources/ios/icon/icon-60@2x.png
#	new file:   resources/ios/icon/icon-60@3x.png
#	new file:   resources/ios/icon/icon-72.png
#	new file:   resources/ios/icon/icon-72@2x.png
#	new file:   resources/ios/icon/icon-76.png
#	new file:   resources/ios/icon/icon-76@2x.png
#	new file:   resources/ios/icon/icon-83.5@2x.png
#	new file:   resources/ios/icon/icon-small.png
#	new file:   resources/ios/icon/icon-small@2x.png
#	new file:   resources/ios/icon/icon-small@3x.png
#	new file:   resources/ios/icon/icon.png
#	new file:   resources/ios/icon/icon@2x.png
#	new file:   resources/ios/splash/Default-568h@2x~iphone.png
#	new file:   resources/ios/splash/Default-667h.png
#	new file:   resources/ios/splash/Default-736h.png
#	new file:   resources/ios/splash/Default-Landscape-736h.png
#	new file:   resources/ios/splash/Default-Landscape@2x~ipad.png
#	new file:   resources/ios/splash/Default-Landscape@~ipadpro.png
#	new file:   resources/ios/splash/Default-Landscape~ipad.png
#	new file:   resources/ios/splash/Default-Portrait@2x~ipad.png
#	new file:   resources/ios/splash/Default-Portrait@~ipadpro.png
#	new file:   resources/ios/splash/Default-Portrait~ipad.png
#	new file:   resources/ios/splash/Default@2x~iphone.png
#	new file:   resources/ios/splash/Default@2x~universal~anyany.png
#	new file:   resources/ios/splash/Default~iphone.png
#	new file:   resources/splash.png
#	new file:   resources/splash.png.md5
#	new file:   src/app/app.component.ts
#	new file:   src/app/app.html
#	new file:   src/app/app.module.ts
#	new file:   src/app/app.scss
#	new file:   src/app/main.ts
#	new file:   src/assets/icon/favicon.ico
#	new file:   src/assets/imgs/iform-bg.png
#	new file:   src/assets/imgs/logo.png
#	new file:   src/index.html
#	new file:   src/manifest.json
#	new file:   src/pages/checkin/checkin.html
#	new file:   src/pages/checkin/checkin.module.ts
#	new file:   src/pages/checkin/checkin.scss
#	new file:   src/pages/checkin/checkin.ts
#	new file:   src/pages/home/home.html
#	new file:   src/pages/home/home.scss
#	new file:   src/pages/home/home.ts
#	new file:   src/pages/login/login.html
#	new file:   src/pages/login/login.module.ts
#	new file:   src/pages/login/login.scss
#	new file:   src/pages/login/login.ts
#	new file:   src/pages/luckydoor/luckydoor.html
#	new file:   src/pages/luckydoor/luckydoor.module.ts
#	new file:   src/pages/luckydoor/luckydoor.scss
#	new file:   src/pages/luckydoor/luckydoor.ts
#	new file:   src/pages/qa/qa.html
#	new file:   src/pages/qa/qa.module.ts
#	new file:   src/pages/qa/qa.scss
#	new file:   src/pages/qa/qa.ts
#	new file:   src/pages/register/register.html
#	new file:   src/pages/register/register.module.ts
#	new file:   src/pages/register/register.scss
#	new file:   src/pages/register/register.ts
#	new file:   src/pages/signature/signature.html
#	new file:   src/pages/signature/signature.module.ts
#	new file:   src/pages/signature/signature.scss
#	new file:   src/pages/signature/signature.ts
#	new file:   src/pipes/pipes.module.ts
#	new file:   src/pipes/search/search.ts
#	new file:   src/pipes/sort/sort.ts
#	new file:   src/providers/rest-api/rest-api.ts
#	new file:   src/service-worker.js
#	new file:   src/theme/variables.scss
#	new file:   tsconfig.json
#	new file:   tslint.json
#	new file:   www/assets/fonts/ionicons.eot
#	new file:   www/assets/fonts/ionicons.scss
#	new file:   www/assets/fonts/ionicons.svg
#	new file:   www/assets/fonts/ionicons.ttf
#	new file:   www/assets/fonts/ionicons.woff
#	new file:   www/assets/fonts/ionicons.woff2
#	new file:   www/assets/fonts/noto-sans-bold.ttf
#	new file:   www/assets/fonts/noto-sans-bold.woff
#	new file:   www/assets/fonts/noto-sans-regular.ttf
#	new file:   www/assets/fonts/noto-sans-regular.woff
#	new file:   www/assets/fonts/noto-sans.scss
#	new file:   www/assets/fonts/roboto-bold.ttf
#	new file:   www/assets/fonts/roboto-bold.woff
#	new file:   www/assets/fonts/roboto-bold.woff2
#	new file:   www/assets/fonts/roboto-light.ttf
#	new file:   www/assets/fonts/roboto-light.woff
#	new file:   www/assets/fonts/roboto-light.woff2
#	new file:   www/assets/fonts/roboto-medium.ttf
#	new file:   www/assets/fonts/roboto-medium.woff
#	new file:   www/assets/fonts/roboto-medium.woff2
#	new file:   www/assets/fonts/roboto-regular.ttf
#	new file:   www/assets/fonts/roboto-regular.woff
#	new file:   www/assets/fonts/roboto-regular.woff2
#	new file:   www/assets/fonts/roboto.scss
#	new file:   www/assets/icon/favicon.ico
#	new file:   www/assets/imgs/iform-bg.png
#	new file:   www/assets/imgs/logo.png
#	new file:   www/build/0.js
#	new file:   www/build/0.js.map
#	new file:   www/build/1.js
#	new file:   www/build/1.js.map
#	new file:   www/build/2.js
#	new file:   www/build/2.js.map
#	new file:   www/build/3.js
#	new file:   www/build/3.js.map
#	new file:   www/build/4.js
#	new file:   www/build/4.js.map
#	new file:   www/build/5.js
#	new file:   www/build/5.js.map
#	new file:   www/build/main.css
#	new file:   www/build/main.css.map
#	new file:   www/build/main.js
#	new file:   www/build/main.js.map
#	new file:   www/build/polyfills.js
#	new file:   www/build/sw-toolbox.js
#	new file:   www/build/vendor.js
#	new file:   www/build/vendor.js.map
#	new file:   www/index.html
#	new file:   www/manifest.json
#	new file:   www/service-worker.js
#
